version: '3.9'

services:

  web:
    build: .
    container_name: web
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: new_db
    image: postgres:16.2-alpine3.19
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
